### ISSUE TITLE
Feature: Automatically save layout position on comment at the last line of each model block

### ISSUE THREAD

**Issue by iki** [mohammed-bahumaish/prisma-editor#13]
```prisma
model Name {
  id Int @id
  // layout(X, Y)
}
```

Tasks:
- [ ] update positions from schema on edit, or undo
- [ ] update schema on each move in editor and on auto-layout, allow undo

**Comment by mohammed-bahumaish** [comment]
@iki  Why would saving layout on the schema will be better?
can you give me more context of what benefits this will bring?
