### ISSUE TITLE
type not being recognized 

### ISSUE THREAD

**Issue by getfoodiespt** [mohammed-bahumaish/prisma-editor#15]
<img width="492" alt="image" src="https://github.com/mohammed-bahumaish/prisma-editor/assets/131707378/66f83326-ff81-4e73-9e1b-3bd6d736ed9e">

**Comment by mohammed-bahumaish** [comment]
@getfoodiespt please share the schema and error message

**Comment by janpio** [comment]
`Address` is a compositve type here, which is only in use for MongoDB: https://www.prisma.io/docs/concepts/components/prisma-client/composite-types
