### ISSUE TITLE
Sign in is broken

### ISSUE THREAD

**Issue by RJWadley** [mohammed-bahumaish/prisma-editor#23]
"The redirect_uri MUST match the registered callback URL for this application". Looks like the allowed redirects might be misconfigured in Github?

For more info: https://docs.github.com/apps/managing-oauth-apps/troubleshooting-authorization-request-errors/#redirect-uri-mismatch

For full context, attempting to sign in redirects to the following:
https://prisma-editor.vercel.app/?error=redirect_uri_mismatch&error_description=The%20redirect_uri%20MUST%20match%20the%20registered%20callback%20URL%20for%20this%20application.&error_uri=https://docs.github.com/apps/managing-oauth-apps/troubleshooting-authorization-request-errors/%23redirect-uri-mismatch&state=e03dYrYtgmm5l50qxpHx8bXRrbik0_C-uYn93kCU4qQ

**Comment by mohammed-bahumaish** [comment]
Yeah, i changed the domain and forgot to update it in Github auth, should work now.

**Comment by RJWadley** [comment]
Works like a charm, thanks!
