### ISSUE TITLE
feat: allow hiding enums

### ISSUE THREAD

**Issue by janpio** [mohammed-bahumaish/prisma-editor#29]
That enums are shown as blocks is nice - unless you have a lot of them and they are not _that_ important to explicitly know about (again). I think it would be nice to have a global option per schema to show (default) or hide them.

Example: 
<img width="1020" alt="image" src="https://github.com/mohammed-bahumaish/prisma-editor/assets/183673/73b0894b-9480-4f29-86ec-ff962e0a8463">
This schema is more enums than models, and looks pretty complex here (and was a lot of work to move all the things around correctly), but really is pretty simple and straightforward with all the enums removed.

**Comment by mohammed-bahumaish** [comment]
will be covered in https://github.com/mohammed-bahumaish/prisma-editor/issues/57
