### ISSUE TITLE
Comment at top of file creates error

### ISSUE THREAD

**Issue by SimplyMerlin** [mohammed-bahumaish/prisma-editor#3]
Hey

![image](https://user-images.githubusercontent.com/30577208/234730028-2d4539de-7076-4410-9c43-658f5d351623.png)

As you can see having a comment at the top of the file leads to errors, even though it's a perfectly valid prisma file.

Really cool project though, keep it up! :)

**Comment by mohammed-bahumaish** [comment]
i fixed that, the error should go away now, but currently when DMMF gets parsed the comment will shift to the top of the first model. will fix that in the future.
