### ISSUE TITLE
feat: publish npm package

### ISSUE THREAD

**Issue by fugudesign** [mohammed-bahumaish/prisma-editor#32]
Hi there!
Thank you a lot for this great job, just exactly what i was looking for.
I thought that could be interesting to have it as a NPM package to be able to integrate in projects.
For example, i'm currently working on a RedwoodJS project which is based on Prisma, and be able to integrate it as a tool in Redwood could be great !

**Comment by mohammed-bahumaish** [comment]
@fugudesign Thanks for the suggestion, great idea. it's been in my radar for sometime, will defiantly do it when i get the time.
