### ISSUE TITLE
fix: generator settings disappear

### ISSUE THREAD

**Issue by MOhhh-ok** [mohammed-bahumaish/prisma-editor#35]
Hi, thanks for great service.

I use @vegardit/prisma-generator-nestjs-dto, and write schema like below.

```
generator nestjsDto {
  provider      = "prisma-generator-nestjs-dto"
  entityPrefix  = "Entity"
}
```

But after using this tool, The data is changed as

```
generator nestjsDto {
    provider      = "prisma-generator-nestjs-dto"
    binaryTargets = ["rhel-openssl-1.0.x", "rhel-openssl-1.0.x"]
}
```
Is there any way to hold my nestjsDto?

**Comment by mohammed-bahumaish** [comment]
will fix that soon, thanks for reporting! @MOhhh-ok
