### ISSUE TITLE
Schema (code and preview) not showing on mobile devices

### ISSUE THREAD

**Issue by mouayed-keziz** [mohammed-bahumaish/prisma-editor#39]
when opening existing schemas in mobile devices, you can see the schema (code and preview) for no longer than a second, then both will disappear (even if you reload the page or reclick on the schema from your schemas).

but, when you open the webite from your desktop, evrything goes back to its normal form.

**Comment by mohammed-bahumaish** [comment]
it should be resolved with the new update
