### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by qdore** [mohammed-bahumaish/prisma-editor#43]
![image](https://github.com/mohammed-bahumaish/prisma-editor/assets/6831829/96274456-cd78-4d75-a5da-88e7ac8e2833)

**Comment by bjrne** [comment]
Same here

**Comment by mouayed-keziz** [comment]
same

**Comment by jonasrht** [comment]
same

**Comment by mohammed-bahumaish** [comment]
fixed
