### ISSUE TITLE
Explode schema when copy pasting prisma file 

### ISSUE THREAD

**Issue by Aarbel** [mohammed-bahumaish/prisma-editor#45]
Thanks a lot for your amazing work @mohammed-bahumaish 

Would it be possible to directly display the schema as "exploded" when copy pasting shema.prisma file content ? (with optimised display of tables function of their links)

Otherwise it takes hours to display a complex schema.

thanks a lot for your help ! 

<img width="1203" alt="image" src="https://github.com/mohammed-bahumaish/prisma-editor/assets/25119847/bb3a1af2-c9ab-488d-94a6-d4b630549dec">

**Comment by aadarsh-nagrath** [comment]
Yup it's a issue

![image](https://github.com/mohammed-bahumaish/prisma-editor/assets/92307537/78b60ce4-3a35-47c2-a590-37345c0d1c11)

Maybe using a force-directed layout algorithm or a tree layout algorithm can be used to arrange the tables.
Anyway nice work @mohammed-bahumaish

**Comment by Aarbel** [comment]
thanks @mohammed-bahumaish
