### ISSUE TITLE
one to many arrows are wrong

### ISSUE THREAD

**Issue by Manubi** [mohammed-bahumaish/prisma-editor#5]
Hi,
thanks for the great tool. As mentioned in the title the arrows for the 1 to many relationships are not correct. I guess.. 
![CleanShot 2023-04-27 at 12 17 18](https://user-images.githubusercontent.com/20935138/234833907-fac13f11-0328-4531-9eb2-12072d8ab4d7.png)

Also how do I save and use autoformat? Thanks

**Comment by mohammed-bahumaish** [comment]
You are right, it's fixed.
Schema is saved automatically after parsing without errors. In future updates when real-time collaboration is completed it will be synced with the server after every update using ws.
Currently the schema is auto formatted only when DMMF is parsed. so you can trigger that by updating a field (or updating) from the graph. In the upcoming days you will be able to click right on the code editor and click 'format'.
