### ISSUE TITLE
Bug to show schema

### ISSUE THREAD

**Issue by dariel26** [mohammed-bahumaish/prisma-editor#50]
The visualization of the schema is a mess after loading the schema. In my schema i added 37 entities.

**Comment by mohammed-bahumaish** [comment]
@dariel26 thanks for the feedback.
could you share a screenshot, and how you suggest improving it?

**Comment by mohammed-bahumaish** [comment]
will be covered in https://github.com/mohammed-bahumaish/prisma-editor/issues/57 https://github.com/mohammed-bahumaish/prisma-editor/issues/56 https://github.com/mohammed-bahumaish/prisma-editor/issues/52
