### ISSUE TITLE
Position is reseted when view a model

### ISSUE THREAD

**Issue by cfercl** [mohammed-bahumaish/prisma-editor#62]
Steps to recreate the error:
- Create a new schema: There is a default models.

![image](https://github.com/user-attachments/assets/6cf97763-4d46-4172-a92b-082cfc92e1ae)

- Click for autolayout

![image](https://github.com/user-attachments/assets/59e9568f-822f-4f26-a7e6-ddc958f7ec5d)

![image](https://github.com/user-attachments/assets/600af5a0-f985-4325-844c-ec100dadf779)

- exit a view the schema again

![image](https://github.com/user-attachments/assets/9f2d9fd5-f99d-459f-ae4d-e45eee85be57)

-the schema position y reseted again

![image](https://github.com/user-attachments/assets/124cd23d-b93f-4bcd-a6ce-2918ff765c92)

![image](https://github.com/user-attachments/assets/e2f3ebeb-690c-4d0b-8f93-f67bcc4c413c)

*sometimes it is showed well but the most times it is showed with position reseted.

**Comment by mohammed-bahumaish** [comment]
thanks for reporting the issue!
it has been a priority fix, which was deployed few minutes ago https://github.com/mohammed-bahumaish/prisma-editor/pull/63 .
could you confirm that it works as expected now?

**Comment by cfercl** [comment]
Thank you Mohammed, It is working OKright now !

That is an awesome work!!
