### ISSUE TITLE
Error parsing attribute "@default"

### ISSUE THREAD

**Issue by atanaskanchev** [mohammed-bahumaish/prisma-editor#7]
`Error parsing attribute "@default"` for array fields. Manually changing it to `role      Role[]    @default([ADMIN])` fixes the issue, but after another change it gets defaulted back to `role      Role[]    @default(ADMIN)`

![image](https://user-images.githubusercontent.com/4958587/236207949-b8f173d2-f179-4f73-a28f-997ffd51bfc8.png)

**Comment by mohammed-bahumaish** [comment]
@atanaskanchev  I've added a fix. can you confirm that it's working as expected now.

**Comment by atanaskanchev** [comment]
Fixed, thank you!
