### ISSUE TITLE
Deleted models are appearing in the diagram

### ISSUE THREAD

**Issue by sagarhimanshu1** [mohammed-bahumaish/prisma-editor#8]
> Every time I delete a model from the schema, it keeps coming up again in the schema when the schema is saved.

**Comment by mohammed-bahumaish** [comment]
@sagarhimanshu1 I couldn't replicate the bug, it seems to be working fine with me. Can you provide more information to help me debug the issue?

**Comment by mohammed-bahumaish** [comment]
it should be resolved with the new update
